-- MySQL Script generated by MySQL Workbench
-- Fri Apr  9 19:55:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lizzard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lizzard` ;

-- -----------------------------------------------------
-- Schema lizzard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lizzard` DEFAULT CHARACTER SET utf8 ;
USE `lizzard` ;

-- -----------------------------------------------------
-- Table `lizzard`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lizzard`.`user` ;

CREATE TABLE IF NOT EXISTS `lizzard`.`user` (
  `id BIGINT` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id BIGINT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lizzard`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lizzard`.`role` ;

CREATE TABLE IF NOT EXISTS `lizzard`.`role` (
  `id BIGINT` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id BIGINT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lizzard`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lizzard`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `lizzard`.`user_roles` (
  `user_id BIGINT` INT NOT NULL,
  `role_id BIGINT` INT NOT NULL,
  INDEX `fk_user_roles_user_idx` (`user_id BIGINT` ASC) VISIBLE,
  INDEX `fk_user_roles_role1_idx` (`role_id BIGINT` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_user`
    FOREIGN KEY (`user_id BIGINT`)
    REFERENCES `lizzard`.`user` (`id BIGINT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_role1`
    FOREIGN KEY (`role_id BIGINT`)
    REFERENCES `lizzard`.`role` (`id BIGINT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT * from role;
